'use strict';

(function(){
  const canvas=document.querySelector('#world'),fatal=document.querySelector('#fatal'),metricsNode=document.querySelector('#metrics'),subtitle=document.querySelector('#subtitle'),authoringToggle=document.querySelector('#authoring-toggle'),authoringPanel=document.querySelector('#authoring-panel'),partSelect=document.querySelector('#part-select'),offsetInputs=[document.querySelector('#offset-x'),document.querySelector('#offset-y'),document.querySelector('#offset-z')],resetPartButton=document.querySelector('#reset-part'),resetAllButton=document.querySelector('#reset-all'),gizmo=document.querySelector('#transform-gizmo'),gizmoAxes=gizmo?Array.from(gizmo.querySelectorAll('[data-axis]')):[];
  const gl=canvas.getContext('webgl',{antialias:true,alpha:false});
  if(!gl){fatal.hidden=false;fatal.textContent='当前浏览器未启用 WebGL。';throw Error('WebGL unavailable');}
  function shader(type,source){const value=gl.createShader(type);gl.shaderSource(value,source);gl.compileShader(value);if(!gl.getShaderParameter(value,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(value));return value;}
  const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 c;uniform mat4 vp;varying vec3 col;void main(){gl_Position=vp*vec4(p,1.);col=c;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 col;void main(){gl_FragColor=vec4(col,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));
  const buffer=gl.createBuffer(),position=gl.getAttribLocation(program,'p'),color=gl.getAttribLocation(program,'c'),vpLocation=gl.getUniformLocation(program,'vp');
  let state={silhouette:false,wallCandidate:'A',view:'three-quarter',variant:'stage',authoring:{enabled:false,selected:'leftWall',offsets:{}}},data=new Float32Array(0),report={},frame=0,drag=null,gizmoDrag=null,camera={target:[0,1.05,0],yaw:.72,pitch:.40,distance:15.8};
  const views={front:{target:[0,1.05,.15],yaw:0,pitch:.24,distance:15.8},'three-quarter':{target:[0,1.0,.1],yaw:.72,pitch:.40,distance:15.8},overhead:{target:[0,.75,.15],yaw:.70,pitch:.83,distance:16.8},comparison:{target:[2.25,1.25,-.65],yaw:0,pitch:.28,distance:10.4},'wall-cap':{target:[2.5,1.38,2.42],yaw:.20,pitch:.20,distance:5.8},'wall-surface':{target:[2.5,.78,2.42],yaw:.08,pitch:.06,distance:4.8},'lattice-comparison':{target:[0,1.05,0],yaw:0,pitch:.12,distance:7.2},'lattice-comparison-close':{target:[0,1.0,0],yaw:0,pitch:.08,distance:5.7},'lattice-comparison-45':{target:[0,1.0,0],yaw:.62,pitch:.22,distance:7.6},'lattice-comparison-overhead':{target:[0,.92,0],yaw:.54,pitch:.58,distance:11.5},'lattice-comparison-mobile':{target:[0,1.05,0],yaw:0,pitch:.12,distance:13.5},'lattice-recommended':{target:[0,1.03,0],yaw:0,pitch:.16,distance:4.75},'gate-front':{target:[0,1.0,.55],yaw:0,pitch:.23,distance:16.8},'gate-45':{target:[0,1.0,.35],yaw:.64,pitch:.36,distance:18.2},'gate-courtyard-front':{target:[-3.55,1.18,2.55],yaw:0,pitch:.18,distance:4.45},'gate-courtyard-45':{target:[-3.55,1.18,2.55],yaw:.56,pitch:.24,distance:4.75},'gate-courtyard-close':{target:[-3.55,1.05,2.55],yaw:0,pitch:.10,distance:3.05},'gate-courtyard-half-close':{target:[-4.15,1.02,2.55],yaw:.08,pitch:.10,distance:2.25},'gate-courtyard-wall-cap':{target:[-3.55,1.72,2.55],yaw:.16,pitch:.24,distance:3.75},'gate-courtyard-overhead':{target:[-3.55,.92,2.55],yaw:.58,pitch:.64,distance:6.8},'gate-side-front':{target:[3.55,1.08,-1.25],yaw:0,pitch:.18,distance:2.85},'gate-side-45':{target:[3.55,1.08,-1.25],yaw:.56,pitch:.10,distance:3.05},'gate-side-close':{target:[3.55,1.02,-1.25],yaw:.10,pitch:.12,distance:2.35},'gate-mobile':{target:[-3.55,1.20,2.55],yaw:.10,pitch:.18,distance:8.40},'gate-side-mobile':{target:[3.55,1.12,-1.25],yaw:.08,pitch:.16,distance:7.00}};
  const axes={x:[1,0,0],y:[0,1,0],z:[0,0,1]},axisIndex={x:0,y:1,z:2};
  function copy(value){return JSON.parse(JSON.stringify(value));}
  function sub(a,b){return a.map(function(value,index){return value-b[index];});}
  function dot(a,b){return a.reduce(function(sum,value,index){return sum+value*b[index];},0);}
  function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
  function norm(a){const length=Math.hypot.apply(null,a)||1;return a.map(function(value){return value/length;});}
  function mul(a,b){const result=new Float32Array(16);for(let j=0;j<4;j++)for(let i=0;i<4;i++)for(let k=0;k<4;k++)result[j*4+i]+=a[k*4+i]*b[j*4+k];return result;}
  function matrix(aspect){const target=camera.target,eye=[target[0]+Math.sin(camera.yaw)*Math.cos(camera.pitch)*camera.distance,target[1]+Math.sin(camera.pitch)*camera.distance,target[2]+Math.cos(camera.yaw)*Math.cos(camera.pitch)*camera.distance],z=norm(sub(eye,target)),x=norm(cross([0,1,0],z)),y=cross(z,x),view=[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1],near=.1,far=100,f=1/Math.tan(.47),projection=[f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0];return mul(projection,view);}
  function project(point,width,height){const m=matrix(width/height),x=point[0],y=point[1],z=point[2],cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],cw=m[3]*x+m[7]*y+m[11]*z+m[15];if(!cw)return null;return{x:(cx/cw*.5+.5)*width,y:(1-(cy/cw*.5+.5))*height,z:cw};}
  function framing(type){const item=(report.metrics&&report.metrics.metadata||[]).find(function(value){return value.type===type&&value.visualBounds;});if(!item)return null;const b=item.visualBounds,p=b.position||[0,0,0],corners=[];[-1,1].forEach(function(x){[0,b.height].forEach(function(y){[-1,1].forEach(function(z){corners.push([p[0]+x*b.width/2,p[1]+y,p[2]+z*b.depth/2]);});});});const width=innerWidth,height=innerHeight,points=corners.map(function(value){return project(value,width,height);}).filter(Boolean),xs=points.map(function(value){return value.x;}),ys=points.map(function(value){return value.y;});const left=Math.min.apply(null,xs),right=Math.max.apply(null,xs),top=Math.min.apply(null,ys),bottom=Math.max.apply(null,ys);return{type:type,centerX:(left+right)/2/width,centerY:(top+bottom)/2/height,width:(right-left)/width,height:(bottom-top)/height,complete:left>=0&&right<=width&&top>=0&&bottom<=height,box:{left:left,right:right,top:top,bottom:bottom},camera:copy(camera)};}
  function sideGateMeta(){return(report.metrics&&report.metrics.metadata||[]).find(function(value){return value.type==='sideGate'&&Array.isArray(value.authoringParts);})||null;}
  function selectedPart(){const meta=sideGateMeta();return meta&&meta.authoringParts.find(function(value){return value.id===state.authoring.selected;})||null;}
  function ensureOffset(id){if(!Array.isArray(state.authoring.offsets[id]))state.authoring.offsets[id]=[0,0,0];return state.authoring.offsets[id];}
  function format(value){return(Math.round(value*1000)/1000).toFixed(3);}
  function syncOffsetInputs(){const values=ensureOffset(state.authoring.selected);offsetInputs.forEach(function(input,index){if(input&&document.activeElement!==input)input.value=format(values[index]);});}
  function refreshPartSelect(){if(!partSelect)return;const meta=sideGateMeta(),parts=meta?meta.authoringParts:[];const current=state.authoring.selected;partSelect.innerHTML='';parts.forEach(function(part){const option=document.createElement('option');option.value=part.id;option.textContent=part.label;partSelect.appendChild(option);});if(parts.length&&!parts.some(function(part){return part.id===current;}))state.authoring.selected=parts[0].id;partSelect.value=state.authoring.selected;syncOffsetInputs();}
  function updateMetrics(){const m=report.metrics||{},budget=report.prototypeBudget||{};metricsNode.textContent=[state.variant.indexOf('gate-stage')===0?'Checkpoint B gate prototype':'Checkpoint A.3 prototype','triangles       '+(m.triangles||0)+' / '+(budget.triangleLimit||7500),'vertices        '+(m.vertices||0)+' / '+(budget.vertexLimit||22500),'static draws    '+(m.drawCalls||0),'GPU materials   '+(m.gpuMaterials||0),'palette roles   '+(m.materialRoleCount||0),'wall default    #d6d8d3','WebGL            '+String(gl.getParameter(gl.VERSION)).replace('WebGL 1.0','1.0')].join('\n');subtitle.textContent=state.authoring.enabled?'部件编辑 · 拖动 X / Y / Z 轴 Gizmo 调整侧门':state.variant==='lattice-comparison'?'格扇密度：A 4×7　/　B 5×8　/　C 5×9':state.variant.indexOf('lattice-recommended')===0?'推荐 B · 5×8 格扇 / closed · half-open':state.variant==='gate-stage-before'||state.variant==='gate-stage-before-half'?'Before · courtyardGate 格子门基线':state.variant==='gate-stage-half'?'courtyardGate 半开 · 竖向拼板门':state.variant==='gate-stage'?'After · courtyardGate 双扇 / sideGate 单扇侧门':'冷灰白墙 #d6d8d3 · DETAIL / LITE 同轮廓对照';}
  function rebuild(){window.JiangnanAuthoringOffsets=state.authoring.offsets;report=JiangnanArchitectureKit.build({silhouette:state.silhouette,wallCandidate:state.wallCandidate,variant:state.variant});data=report.vertices;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);updateMetrics();refreshPartSelect();document.documentElement.setAttribute('data-checkpoint-a-ready','true');return report;}
  function updateGizmo(){if(!gizmo)return;const part=selectedPart();if(!state.authoring.enabled||!part){gizmo.hidden=true;return;}const width=innerWidth,height=innerHeight,origin=project(part.position,width,height);if(!origin||origin.z<=0){gizmo.hidden=true;return;}gizmo.hidden=false;gizmo.style.left=origin.x+'px';gizmo.style.top=origin.y+'px';gizmoAxes.forEach(function(handle){const axis=handle.dataset.axis,vector=axes[axis],endpoint=project([part.position[0]+vector[0]*.62,part.position[1]+vector[1]*.62,part.position[2]+vector[2]*.62],width,height);if(!endpoint){handle.hidden=true;return;}handle.hidden=false;const dx=endpoint.x-origin.x,dy=endpoint.y-origin.y,length=Math.max(34,Math.min(92,Math.hypot(dx,dy))),angle=Math.atan2(dy,dx)*180/Math.PI;handle.style.width=length+'px';handle.style.transform='translateY(-50%) rotate('+angle+'deg)';});}
  function draw(){const dpr=Math.min(devicePixelRatio||1,1.5),width=Math.max(1,Math.round(innerWidth*dpr)),height=Math.max(1,Math.round(innerHeight*dpr));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}gl.viewport(0,0,width,height);if(state.silhouette)gl.clearColor(.82,.84,.81,1);else gl.clearColor(.65,.71,.69,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniformMatrix4fv(vpLocation,false,matrix(width/height));gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(color);gl.vertexAttribPointer(color,3,gl.FLOAT,false,24,12);gl.drawArrays(gl.TRIANGLES,0,data.length/6);updateGizmo();frame=requestAnimationFrame(draw);}
  function setView(name){if(!views[name])throw Error('Unknown preview view: '+name);state.view=name;camera=copy(views[name]);document.querySelectorAll('[data-view]').forEach(function(button){button.classList.toggle('active',button.dataset.view===name);});}
  function setCamera(value){if(!value||!Array.isArray(value.target))throw Error('setCamera requires target/yaw/pitch/distance');camera={target:value.target.slice(0,3),yaw:Number(value.yaw)||0,pitch:Number(value.pitch)||0,distance:Number(value.distance)||10};state.view='custom';return copy(camera);}
  function setSilhouette(value){state.silhouette=!!value;document.querySelector('#silhouette').classList.toggle('active',state.silhouette);return rebuild();}
  function setWallCandidate(value){state.wallCandidate=value==='B'?'B':'A';return rebuild();}
  function setVariant(value){state.variant=['lattice-comparison','lattice-recommended','lattice-recommended-single','lattice-baseline-single','gate-stage','gate-stage-before','gate-stage-half','gate-stage-before-half','gate-stage-wood-before'].indexOf(value)>=0?value:'stage';return rebuild();}
  function setClean(value){document.querySelectorAll('header,nav,#legend,#metrics,#authoring-panel').forEach(function(element){element.hidden=!!value;});if(gizmo)gizmo.hidden=!!value||!state.authoring.enabled;}
  function setAuthoringEnabled(value){state.authoring.enabled=!!value;if(authoringToggle)authoringToggle.classList.toggle('active',state.authoring.enabled);if(authoringPanel)authoringPanel.hidden=!state.authoring.enabled;if(state.authoring.enabled&&state.variant.indexOf('gate-stage')!==0)setVariant('gate-stage');updateMetrics();refreshPartSelect();updateGizmo();return state.authoring.enabled;}
  function selectAuthoringPart(id){const meta=sideGateMeta();if(meta&&meta.authoringParts.some(function(part){return part.id===id;})){state.authoring.selected=id;if(partSelect)partSelect.value=id;syncOffsetInputs();updateGizmo();}return state.authoring.selected;}
  function resetAuthoring(id){if(id)delete state.authoring.offsets[id];else state.authoring.offsets={};rebuild();syncOffsetInputs();return copy(state.authoring.offsets);}
  document.querySelectorAll('[data-view]').forEach(function(button){button.addEventListener('click',function(){setView(button.dataset.view);});});
  document.querySelector('#silhouette').addEventListener('click',function(){setSilhouette(!state.silhouette);});document.querySelector('#wall-candidate').addEventListener('click',function(){setWallCandidate(state.wallCandidate==='A'?'B':'A');});
  if(authoringToggle)authoringToggle.addEventListener('click',function(){setAuthoringEnabled(!state.authoring.enabled);});
  if(partSelect)partSelect.addEventListener('change',function(){selectAuthoringPart(partSelect.value);});
  offsetInputs.forEach(function(input,index){if(!input)return;input.addEventListener('change',function(){const number=Number(input.value);if(!Number.isFinite(number)){syncOffsetInputs();return;}ensureOffset(state.authoring.selected)[index]=Math.max(-3,Math.min(3,number));rebuild();});});
  if(resetPartButton)resetPartButton.addEventListener('click',function(){resetAuthoring(state.authoring.selected);});if(resetAllButton)resetAllButton.addEventListener('click',function(){resetAuthoring();});
  gizmoAxes.forEach(function(handle){handle.addEventListener('pointerdown',function(event){if(!state.authoring.enabled)return;const part=selectedPart(),axis=handle.dataset.axis,vector=axes[axis],origin=part&&project(part.position,innerWidth,innerHeight),endpoint=part&&project([part.position[0]+vector[0],part.position[1]+vector[1],part.position[2]+vector[2]],innerWidth,innerHeight);if(!part||!origin||!endpoint)return;const dx=endpoint.x-origin.x,dy=endpoint.y-origin.y,length=Math.hypot(dx,dy);if(length<8)return;event.preventDefault();event.stopPropagation();handle.setPointerCapture(event.pointerId);const offset=ensureOffset(part.id);gizmoDrag={id:event.pointerId,axis:axis,index:axisIndex[axis],startX:event.clientX,startY:event.clientY,startValue:offset[axisIndex[axis]],dirX:dx/length,dirY:dy/length,pixelsPerWorld:length};});handle.addEventListener('pointermove',function(event){if(!gizmoDrag||gizmoDrag.id!==event.pointerId)return;event.preventDefault();const delta=(event.clientX-gizmoDrag.startX)*gizmoDrag.dirX+(event.clientY-gizmoDrag.startY)*gizmoDrag.dirY,value=Math.max(-3,Math.min(3,gizmoDrag.startValue+delta/gizmoDrag.pixelsPerWorld));ensureOffset(state.authoring.selected)[gizmoDrag.index]=Math.round(value*1000)/1000;rebuild();});function end(event){if(gizmoDrag&&gizmoDrag.id===event.pointerId){gizmoDrag=null;syncOffsetInputs();}}handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);});
  canvas.addEventListener('pointerdown',function(event){drag={id:event.pointerId,x:event.clientX,y:event.clientY};canvas.setPointerCapture(event.pointerId);});canvas.addEventListener('pointermove',function(event){if(!drag||drag.id!==event.pointerId)return;camera.yaw-=(event.clientX-drag.x)*.007;camera.pitch=Math.max(.08,Math.min(1.35,camera.pitch+(event.clientY-drag.y)*.005));drag.x=event.clientX;drag.y=event.clientY;});canvas.addEventListener('pointerup',function(){drag=null;});canvas.addEventListener('pointercancel',function(){drag=null;});canvas.addEventListener('wheel',function(event){event.preventDefault();camera.distance=Math.max(2.2,Math.min(24,camera.distance+event.deltaY*.01));},{passive:false});
  gl.enable(gl.DEPTH_TEST);rebuild();setView('three-quarter');frame=requestAnimationFrame(draw);
  window.JiangnanPreview={setView:setView,setCamera:setCamera,setSilhouette:setSilhouette,setWallCandidate:setWallCandidate,setVariant:setVariant,setClean:setClean,setAuthoringEnabled:setAuthoringEnabled,selectAuthoringPart:selectAuthoringPart,resetAuthoring:resetAuthoring,rebuild:rebuild,getMetrics:function(){return copy(report.metrics);},getReport:function(){const value=copy(report);delete value.vertices;return value;},getState:function(){return copy(state);},getCamera:function(){return copy(camera);},getFraming:framing,getAuthoringOffsets:function(){return copy(state.authoring.offsets);},webglVersion:String(gl.getParameter(gl.VERSION))};
})();
