'use strict';

(function(){
  function woodBand(seed,salt,style){return JiangnanRandom.signed(seed,salt)*style.woodVariation*.22;}
  function roofRack(sink,spec,style){
    sink.withTransform({position:spec.position},function(){
      sink.scope('roof-rack/columns','wood',function(){[-1,1].forEach(function(x){[-1,1].forEach(function(z){sink.box(x*spec.width*.42,spec.baseY*.5,z*spec.depth*.38,style.columnRadius*1.6,spec.baseY,style.columnRadius*1.6,'wood',woodBand(spec.seed,'post-'+x+'/'+z,style));});});});
      sink.scope('roof-rack/beams','wood',function(){sink.box(0,spec.baseY-.08,-spec.depth*.38,spec.width*.94,style.beamThickness,style.beamThickness,'wood');sink.box(0,spec.baseY-.08,spec.depth*.38,spec.width*.94,style.beamThickness,style.beamThickness,'wood');});
      JiangnanRoof.build(sink,{id:spec.id,width:spec.width,depth:spec.depth,baseY:spec.baseY,roofHeight:spec.roofHeight,eaveOverhang:spec.eaveOverhang,mode:spec.mode,seed:spec.seed},style);
      sink.anchor({id:spec.id+'/front/eave/lantern-01',position:[spec.position[0],spec.position[1]+spec.baseY-.18,spec.position[2]+spec.depth/2+spec.eaveOverhang],normal:[0,0,1],tags:['eave-hang','lantern']});
    });
  }
  function measureRoof(style,mode){const sink=JiangnanGeometrySink.create({style:style});JiangnanRoof.build(sink,{id:'roofPrototype/measurement-'+mode.toLowerCase(),width:3.35,depth:2.3,baseY:1.72,roofHeight:.77,eaveOverhang:.34,mode:mode,seed:63011},style);const result=sink.finish();return{triangles:result.metrics.triangles,vertices:result.metrics.vertices,drawCalls:1,gpuMaterials:1,visualEnvelope:result.metrics.metadata[0].visualEnvelope};}
  function measureLattice(style,gridX,gridY){const sink=JiangnanGeometrySink.create({style:style});JiangnanLatticeFacadeUnit.build(sink,{id:'latticeFacadeUnit/measurement-'+gridX+'x'+gridY,position:[0,0,0],width:1.45,height:2.05,depth:.075,kind:'door',gridX:gridX,gridY:gridY,openMode:'closed',hingeSide:'left',seed:52011},style);const result=sink.finish();return{gridX:gridX,gridY:gridY,triangles:result.metrics.triangles,vertices:result.metrics.vertices};}
  function latticeComparison(sink,style){[[-2,4,7,'a-4x7'],[0,5,8,'b-5x8'],[2,5,9,'c-5x9']].forEach(function(value){JiangnanLatticeFacadeUnit.build(sink,{id:'latticeFacadeUnit/'+value[3],position:[value[0],0,0],width:1.45,height:2.05,depth:.075,kind:'door',gridX:value[1],gridY:value[2],openMode:'closed',hingeSide:'left',seed:52011},style);});}
  function latticeSingle(sink,style,gridX,gridY,id){JiangnanLatticeFacadeUnit.build(sink,{id:id,position:[0,0,0],width:1.45,height:2.05,depth:.075,kind:'door',gridX:gridX,gridY:gridY,openMode:'closed',hingeSide:'left',seed:52011},style);}
  function latticeRecommended(sink,style,halfOpen){if(halfOpen){JiangnanLatticeFacadeUnit.build(sink,{id:'latticeFacadeUnit/recommended-closed',position:[-.86,0,0],width:1.45,height:2.05,depth:.075,kind:'door',gridX:5,gridY:8,openMode:'closed',hingeSide:'left',seed:52011},style);JiangnanLatticeFacadeUnit.build(sink,{id:'latticeFacadeUnit/recommended-half-open',position:[.86,0,0],width:1.45,height:2.05,depth:.075,kind:'door',gridX:5,gridY:8,openMode:'half-open',hingeSide:'left',openAngle:Math.PI*.48,seed:52012},style);}else latticeSingle(sink,style,5,8,'latticeFacadeUnit/recommended-single');}
  function measureGate(style,type){const sink=JiangnanGeometrySink.create({style:style});if(type==='courtyardGate')JiangnanCourtyardGate.build(sink,{id:'courtyardGate/measurement',position:[0,0,0],seed:71001},style);else JiangnanSideGate.build(sink,{id:'sideGate/measurement',position:[0,0,0],seed:71002},style);const result=sink.finish();return{type:type,triangles:result.metrics.triangles,vertices:result.metrics.vertices,drawCalls:1,gpuMaterials:1};}
  function gateWallPair(sink,gate,wallId,z,startX,endX,style){const post=gate.postThickness||style.columnRadius*2.5,half=gate.openingWidth/2+post,joinLeft=gate.position[0]-half,joinRight=gate.position[0]+half,wallHeight=1.48;if(joinLeft-startX>.12)JiangnanCourtyardWall.build(sink,{id:wallId+'/wall-left',start:[startX,z],end:[joinLeft,z],baseY:0,wallHeight:wallHeight,thickness:.25,capType:'tiled',cornerType:'end-cap',seed:gate.seed+11},style);if(endX-joinRight>.12)JiangnanCourtyardWall.build(sink,{id:wallId+'/wall-right',start:[joinRight,z],end:[endX,z],baseY:0,wallHeight:wallHeight,thickness:.25,capType:'tiled',cornerType:'end-cap',seed:gate.seed+12},style);}
  function gateStage(sink,style,doorThicknessProfile,courtyardOpenMode){if(!sink)throw Error('gateStage requires a geometry sink');const profile=doorThicknessProfile||'thin';const courtyard={id:'courtyardGate/test-bay',type:'courtyardGate',position:[-3.55,0,2.55],openingWidth:2.35,gateHeight:2.22,gateDepth:.52,roofScale:1,eaveOverhang:.16,doorLeafCount:2,doorOpenAngle:Math.PI*.20,doorOpenMode:courtyardOpenMode||'open',roofComplexity:'LITE',doorThicknessProfile:profile,seed:71011,postThickness:style.columnRadius*2.5,beamThickness:style.beamThickness*1.24};const side={id:'sideGate/test-bay',type:'sideGate',position:[3.55,0,-1.25],openingWidth:1.48,gateHeight:1.86,gateDepth:.38,roofScale:.80,eaveOverhang:.12,doorLeafCount:2,doorOpenAngle:Math.PI*.18,roofComplexity:'LITE',doorThicknessProfile:profile,seed:71021,postThickness:style.columnRadius*2.2,beamThickness:style.beamThickness*1.10};gateWallPair(sink,courtyard,'courtyardWall/gate-courtyard',courtyard.position[2],-7,.25,style);gateWallPair(sink,side,'courtyardWall/gate-side',side.position[2],.25,6.75,style);JiangnanCourtyardGate.build(sink,courtyard,style);JiangnanSideGate.build(sink,side,style);return{courtyard:courtyard,side:side};}
  function build(options){
    options=options||{};
    const style=JiangnanStyle.resolve(Object.assign({},options.styleOverrides||{},options.wallCandidate==='B'?{wallColor:JiangnanStyle.profile.wallColorCandidates.B}:{wallColor:JiangnanStyle.profile.wallColorCandidates.A}));
    const sink=JiangnanGeometrySink.create({style:style,silhouette:!!options.silhouette});
    if(options.variant==='lattice-comparison')latticeComparison(sink,style);else if(options.variant==='lattice-recommended')latticeRecommended(sink,style,true);else if(options.variant==='lattice-recommended-single')latticeRecommended(sink,style,false);else if(options.variant==='lattice-baseline-single')latticeSingle(sink,style,4,7,'latticeFacadeUnit/baseline-single');else if(options.variant==='gate-stage'||options.variant==='gate-stage-before'||options.variant==='gate-stage-half'||options.variant==='gate-stage-before-half'||options.variant==='gate-stage-wood-before'){if(!options.silhouette)sink.scope('preview/plinth','stone',function(){sink.box(0,-.055,0,14.8,.10,7.6,'stone');});if(options.variant==='gate-stage-wood-before')style.doorBoardColor=style.woodColor;gateStage(sink,style,options.variant==='gate-stage-wood-before'?'thin':options.variant.indexOf('before')>=0?'legacy':'thin',options.variant.indexOf('half')>=0?'half-open':null);}else{
      if(!options.silhouette)sink.scope('preview/plinth','stone',function(){sink.box(0,-.055,0,14.8,.10,7.6,'stone');});
      JiangnanCourtyardWall.build(sink,{id:'courtyardWall/segment-a',start:[-7,2.55],end:[7,2.55],baseY:0,wallHeight:1.48,thickness:.25,capType:'tiled',cornerType:'both',seed:41021},style);
      JiangnanCourtyardWall.build(sink,{id:'courtyardWall/return-east',start:[7,2.55],end:[7,.9],baseY:0,wallHeight:1.48,thickness:.25,capType:'tiled',cornerType:'end-cap',seed:41022},style);
      JiangnanLatticeFacadeUnit.build(sink,{id:'latticeFacadeUnit/closed-a',position:[-5.25,0,-.65],width:1.45,height:2.05,depth:.075,kind:'door',gridX:5,gridY:8,openMode:'closed',hingeSide:'left',seed:52011},style);
      JiangnanLatticeFacadeUnit.build(sink,{id:'latticeFacadeUnit/half-open-b',position:[-3.45,0,-.65],width:1.45,height:2.05,depth:.075,kind:'door',gridX:5,gridY:8,openMode:'half-open',hingeSide:'left',openAngle:Math.PI*.48,seed:52012},style);
      roofRack(sink,{id:'roofPrototype/detail-a',position:[.15,0,-.65],width:3.35,depth:2.3,baseY:1.72,roofHeight:.77,eaveOverhang:.34,mode:'DETAIL',seed:63011},style);
      roofRack(sink,{id:'roofPrototype/lite-a',position:[4.65,0,-.65],width:3.35,depth:2.3,baseY:1.72,roofHeight:.77,eaveOverhang:.34,mode:'LITE',seed:63011},style);
    }
    const result=sink.finish();result.style=style;result.roofComparison={DETAIL:measureRoof(style,'DETAIL'),LITE:measureRoof(style,'LITE'),sharedEnvelope:true};result.latticeComparison={A:measureLattice(style,4,7),B:measureLattice(style,5,8),C:measureLattice(style,5,9)};result.selectedLattice={id:'B',gridX:5,gridY:8,reason:'Creator-frozen jiangnan-v1 default: lowest-cost denser grid that remains legible at desktop and 390x844.'};result.gateComparison={courtyardGate:measureGate(style,'courtyardGate'),sideGate:measureGate(style,'sideGate'),sharedComponents:['gate-frame','roof','courtyardWall','latticeFacadeUnit','plankDoorLeaf']};result.renderPolicy={checkpointA:{staticArchitectureDrawCalls:1,staticBody:'generation-time-merged'},future:{staticBody:'generation-time-merged',optionalIndependentRanges:['animated-door-leaf','special-transparent-part'],hardDrawCallLimit:null}};result.prototypeBudget={scope:'Checkpoint B gate validation stage',triangleLimit:7500,vertexLimit:22500,staticArchitectureDrawCallTarget:1,gateLimits:{courtyardGate:2600,sideGate:1800,combinedNewArchitecture:7000}};result.futureProductionBudget={scope:'Checkpoint C/D per production assembly',status:'deferred',note:'Budgets for mainHall, sideHouse, gates and courtyardWall will be set separately after prototype review.'};return result;
  }
  window.JiangnanArchitectureKit={build:build};
})();
