'use strict';

(function(){
  function build(sink,spec,style){
    const position=spec.position||[0,0,0],openingWidth=spec.openingWidth||2.35,gateHeight=spec.gateHeight||2.22,gateDepth=spec.gateDepth||.52,leafCount=spec.doorLeafCount||2,openAngle=Number.isFinite(spec.doorOpenAngle)?spec.doorOpenAngle:Math.PI*.20,roofScale=spec.roofScale||1,eaveOverhang=spec.eaveOverhang||.16,roofComplexity=(spec.roofComplexity||'LITE').toUpperCase(),frame=JiangnanGateFrame.build(sink,{id:spec.id,position:position,openingWidth:openingWidth,gateHeight:gateHeight,gateDepth:gateDepth,postThickness:spec.postThickness||style.columnRadius*2.5,beamThickness:spec.beamThickness||style.beamThickness*1.24,seed:spec.seed},style),legacyLeafDepth=Math.min(gateDepth*.76,.42),legacyLeafFrame=style.beamThickness*.7,legacyBar=legacyLeafFrame*.22,legacy=spec.doorThicknessProfile==='legacy',leafDepthScale=legacy? .76:(Number.isFinite(spec.doorLeafDepthScale)?spec.doorLeafDepthScale:.42),leafFrameScale=legacy?1:(Number.isFinite(spec.doorFrameScale)?spec.doorFrameScale:.70),leafBarScale=legacy?1:(Number.isFinite(spec.doorBarScale)?spec.doorBarScale:.72),barDepthScale=legacy? .72:(Number.isFinite(spec.doorBarDepthScale)?spec.doorBarDepthScale:.40),doorDepth=legacy?legacyLeafDepth:Math.min(gateDepth*leafDepthScale,.30),doorFrameThickness=legacy?legacyLeafFrame:legacyLeafFrame*leafFrameScale,doorBarThickness=legacy?legacyBar:legacyBar*leafFrameScale*leafBarScale,gap=.055,leafWidth=(openingWidth-gap*(leafCount-1))/leafCount,leafHeight=gateHeight-frame.beamThickness*1.9-.12,doorOpenMode=spec.doorOpenMode||(spec.type==='sideGate'?'half-open':'open');
    const doorY=0,plank=!!(!legacy&&(spec.type==='courtyardGate'||spec.type==='sideGate'));
    for(let i=0;i<leafCount;i++){
      const isLeft=i===0,leafId=spec.id+'/door/leaf-'+(isLeft?'left':'right'),offset=(i-(leafCount-1)/2)*(leafWidth+gap);
      const doorSpec={id:leafId,position:[position[0]+offset,doorY,position[2]],width:leafWidth,height:leafHeight,depth:doorDepth,frameThickness:doorFrameThickness,kind:'door',openMode:doorOpenMode,hingeSide:isLeft?'left':'right',openAngle:openAngle,seed:(spec.seed||1)+i*7};
      if(plank)JiangnanPlankDoorLeaf.build(sink,Object.assign({},doorSpec,{boardCount:spec.type==='sideGate'?5:6,seamGap:spec.type==='sideGate'?.014:.012,braceCount:spec.type==='sideGate'?0:1,braceThickness:.052,braceDepth:.048,boardColor:style.doorBoardColor||sink.tone(sink.color('wood'),spec.type==='sideGate'?.13:.11)}),style);
      else JiangnanLatticeFacadeUnit.build(sink,Object.assign({},doorSpec,{barThickness:doorBarThickness,barDepthScale:barDepthScale,backing:legacy,gridX:5,gridY:8}),style);
    }
    sink.withTransform({position:position},function(){JiangnanRoof.build(sink,{id:spec.id,width:(openingWidth+frame.postThickness*2)*roofScale,depth:gateDepth*roofScale,baseY:gateHeight+frame.beamThickness*.08,roofHeight:.40*roofScale,eaveOverhang:eaveOverhang*roofScale,mode:roofComplexity,seed:(spec.seed||1)+31,showRafters:roofComplexity==='DETAIL',ridgeScale:.92},style);});
    const z=position[2],roofY=gateHeight+frame.beamThickness*.08+.40*roofScale;
    sink.anchor({id:spec.id+'/front/eave/lantern-left',position:[position[0]-(openingWidth*.5+frame.postThickness)*roofScale,position[1]+roofY-.12,z+gateDepth*.5*roofScale+eaveOverhang*roofScale],normal:[0,0,1],tags:['eave-hang','lantern']});
    sink.anchor({id:spec.id+'/front/eave/lantern-right',position:[position[0]+(openingWidth*.5+frame.postThickness)*roofScale,position[1]+roofY-.12,z+gateDepth*.5*roofScale+eaveOverhang*roofScale],normal:[0,0,1],tags:['eave-hang','lantern']});
    if(spec.type==='sideGate')sink.anchor({id:spec.id+'/front/eave/lantern-01',position:[position[0],position[1]+roofY-.12,z+gateDepth*.5*roofScale+eaveOverhang*roofScale],normal:[0,0,1],tags:['eave-hang','lantern']});
    sink.anchor({id:spec.id+'/doorstep/left',position:[position[0]-openingWidth*.34,position[1],z+gateDepth*.55],normal:[0,0,1],tags:['doorstep','prop']});
    sink.anchor({id:spec.id+'/doorstep/right',position:[position[0]+openingWidth*.34,position[1],z+gateDepth*.55],normal:[0,0,1],tags:['doorstep','prop']});
    sink.anchor({id:spec.id+'/side/prop-left',position:[frame.leftPost,position[1]+.55,z+gateDepth*.55],normal:[0,0,1],tags:['wall-prop','jar','wood-stack']});
    sink.anchor({id:spec.id+'/side/prop-right',position:[frame.rightPost,position[1]+.55,z+gateDepth*.55],normal:[0,0,1],tags:['wall-prop','jar','wood-stack']});
    sink.metadata({id:spec.id,type:spec.type||'courtyardGate',openingWidth:openingWidth,gateHeight:gateHeight,gateDepth:gateDepth,roofScale:roofScale,eaveOverhang:eaveOverhang,doorLeafCount:leafCount,doorOpenAngle:openAngle,doorOpenMode:doorOpenMode,roofComplexity:roofComplexity,doorThicknessProfile:legacy?'legacy':'thin',doorComponent:plank?'plankDoorLeaf':'latticeFacadeUnit',doorConstruction:plank?'vertical-plank':'lattice',boardCount:plank?(spec.type==='sideGate'?5:6):null,seamGap:plank?(spec.type==='sideGate'?.014:.012):null,braceCount:plank?(spec.type==='sideGate'?0:1):null,doorLeafDepth:doorDepth,doorLeafDepthScale:leafDepthScale,doorLeafDepthRatioToLegacy:doorDepth/legacyLeafDepth,doorFrameThickness:doorFrameThickness,doorBarThickness:plank ? null : doorBarThickness,doorBarDepthScale:plank ? null : barDepthScale,doorBarDepth:plank ? null : doorDepth*barDepthScale,doorBarWidthRatioToLegacy:plank ? null : doorBarThickness/legacyBar,doorBarDepthRatioToLegacy:plank ? null : (doorDepth*barDepthScale)/(legacyLeafDepth*.72),visualBounds:{position:position,width:openingWidth+frame.postThickness*2,height:gateHeight+.40*roofScale,depth:gateDepth+eaveOverhang*2},gameplayFootprint:null});
    return{openingWidth:openingWidth,gateHeight:gateHeight,gateDepth:gateDepth,doorLeafCount:leafCount,doorOpenAngle:openAngle,doorOpenMode:doorOpenMode,doorLeafDepth:doorDepth,doorFrameThickness:doorFrameThickness,doorBarThickness:doorBarThickness,doorBarDepthScale:barDepthScale,roofComplexity:roofComplexity,frame:frame};
  }
  window.JiangnanCourtyardGate={build:build};
})();
